### ISSUE TITLE
[Feature] - more sophisticated miranum connect github template with hexagonal architecture

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum-connect#167]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [ ] Prioritised

# Description

The goal of this ticket is to develop a comprehensive GitHub template for a Miranum project that employs Hexagonal Architecture, also known as Ports and Adapters Architecture. This template should serve as a foundation for users aiming to create more complex, domain-heavy projects, leveraging the key benefits of this architectural style - loose coupling, high testability, and driver-port independence.

This GitHub template aims to provide a robust starting point for users to develop their own Miranum projects with a well-structured, adaptable and maintainable architecture. By demonstrating Hexagonal Architecture principles in action, this template can guide users in building sophisticated, domain-heavy applications with Miranum.

The [simple example](https://github.com/Miragon/miranum-connect/tree/main/examples/simple-example) can be used as a starting point.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] **Template Structure**
- [ ] **Workers**
- [ ] **Correlate a Message**
- [ ] **Start a Process**
- [ ] **Documentation**
```

**Comment by rami-nk** [comment]
@Hafflgav What name would you suggest for this? Simply: miranum-connect-hexagonal-template?

**Comment by Hafflgav** [comment]
Yes @rami-nk - that's also my favourite!
