### ISSUE TITLE
[Bug] - Fix JSON variable handling in the worker

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-connect#204]
**Describe the bug**
As soon as there is a process variable of type JSON the worker fails to map the variables. This is caused by the `Camunda7WorkerAdapter` or to be more specific in the `Camunda7PojoMapper` class. 
See exception below:

```
2023-09-15T09:07:51.042+02:00 ERROR 9632 --- [criptionManager] i.m.m.c.a.i.c.w.Camunda7WorkerAdapter    : 
Error while executing external task com.fasterxml.jackson.databind.exc.MismatchedInputException: 
Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): 
no String-argument constructor/factory method to deserialize from String value ('A')
at [Source: (String)""A""; line: 1, column: 1]
```

The only current work around is to ensure that there are no JSON variables in the process. This can be done by overriding the JSON variable in the input of an external service task. This is exemplary shown in the screenshot below: 
<img width="475" alt="image" src="https://github.com/Miragon/miranum-connect/assets/30292227/a0c8e471-6f9a-46ef-9429-d55a88dad610">

**Expected behaviour**
Fetching and mapping JSON variables to pojos in the context of a Camunda 7 worker should not cause any exception.

**Comment by dominikhorn93** [comment]
Could be solved by: https://github.com/Miragon/miranum-connect/pull/207
